import { jsPDF } from "jspdf";

// Very lightweight markdown-ish renderer into a jsPDF document.
// Handles: # / ## / ### headings, - or * bullets, numbered lists, `code`,
// **bold**, and paragraph text. Designed for AI-generated study notes.
export function downloadStudyPdf(opts: {
  title: string;
  subtitle?: string;
  markdown: string;
  filename?: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginX = 48;
  const maxW = pageW - marginX * 2;
  let y = 60;

  const ensure = (h: number) => {
    if (y + h > pageH - 48) {
      doc.addPage();
      y = 60;
    }
  };

  // Header band
  doc.setFillColor(221, 238, 255);
  doc.rect(0, 0, pageW, 40, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(80, 90, 120);
  doc.text("StudyMate AI · Study Notes", marginX, 26);

  // Title
  doc.setTextColor(30, 35, 60);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const titleLines = doc.splitTextToSize(opts.title, maxW);
  doc.text(titleLines, marginX, y);
  y += titleLines.length * 26;

  if (opts.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(110, 115, 140);
    const sub = doc.splitTextToSize(opts.subtitle, maxW);
    doc.text(sub, marginX, y);
    y += sub.length * 14 + 4;
  }

  doc.setDrawColor(210, 220, 240);
  doc.line(marginX, y, pageW - marginX, y);
  y += 18;

  const writeWrapped = (text: string, size: number, style: "normal" | "bold", color: [number, number, number], indent = 0) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxW - indent);
    for (const line of lines) {
      ensure(size + 4);
      doc.text(line, marginX + indent, y);
      y += size + 4;
    }
  };

  const stripInline = (s: string) => s.replace(/\*\*(.+?)\*\*/g, "$1").replace(/`([^`]+)`/g, "$1").replace(/\*(.+?)\*/g, "$1");

  const lines = opts.markdown.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) { y += 6; continue; }

    if (/^###\s+/.test(line)) {
      y += 4;
      writeWrapped(stripInline(line.replace(/^###\s+/, "")), 12, "bold", [60, 70, 110]);
      continue;
    }
    if (/^##\s+/.test(line)) {
      y += 8;
      writeWrapped(stripInline(line.replace(/^##\s+/, "")), 15, "bold", [45, 55, 100]);
      continue;
    }
    if (/^#\s+/.test(line)) {
      y += 10;
      writeWrapped(stripInline(line.replace(/^#\s+/, "")), 18, "bold", [30, 40, 90]);
      continue;
    }
    const bullet = line.match(/^\s*[-*]\s+(.*)/);
    if (bullet) {
      ensure(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(90, 110, 180);
      doc.setFontSize(11);
      doc.text("•", marginX + 4, y);
      writeWrapped(stripInline(bullet[1]), 11, "normal", [55, 60, 80], 16);
      continue;
    }
    const numbered = line.match(/^\s*(\d+)\.\s+(.*)/);
    if (numbered) {
      ensure(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(90, 110, 180);
      doc.setFontSize(11);
      doc.text(`${numbered[1]}.`, marginX + 4, y);
      writeWrapped(stripInline(numbered[2]), 11, "normal", [55, 60, 80], 22);
      continue;
    }
    writeWrapped(stripInline(line), 11, "normal", [50, 55, 75]);
  }

  // Footer with page numbers
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(150, 155, 175);
    doc.text(`Page ${i} of ${pageCount}`, pageW - marginX, pageH - 24, { align: "right" });
    doc.text("Generated by StudyMate AI", marginX, pageH - 24);
  }

  const safeName = (opts.filename ?? opts.title).replace(/[^a-z0-9-_ ]/gi, "_").slice(0, 80) || "studymate";
  doc.save(`${safeName}.pdf`);
}